title: Internship blog
author: Sander Forrer
email: r0809853@student.thomasmore.bbe
description: > # this means to ignore newlines until "show_exerpts:"
  Internship blog
show_excerpts: true # set to true to show excerpts on the homepage
#baseurl: /texture
remote_theme: thelehhman/texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Internship blog NVISO
  tagline: Sander Forrer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: 
    github:  X3ntr
    linkedIn: in/sanderforrer
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed